#!/bin/bash

# Shared helpers for wiki scripts.

log_info() {
    echo "INFO: $*"
}

log_warn() {
    echo "WARNING: $*" >&2
}

log_error() {
    echo "ERROR: $*" >&2
}

die() {
    log_error "$*"
    exit 1
}

default_wikis_dir() {
    echo "${WIKIS_DIR:-${HOME}/.claude/wikis}"
}

detect_project_root() {
    local git_root
    git_root="$(git rev-parse --show-toplevel 2>/dev/null)" || true
    if [[ -n "$git_root" ]]; then
        echo "$git_root"
    fi
}

project_wikis_dir() {
    local root
    root="$(detect_project_root)"
    if [[ -n "$root" ]]; then
        echo "$root/.claude/wikis"
    fi
}

default_codemap_pref_file() {
    echo "${CODEMAP_PREF_FILE:-$(default_wikis_dir)/codemap.preference}"
}

resolve_wiki_path() {
    local input="$1"
    local base

    if [[ -d "$input" ]]; then
        echo "$input"
        return 0
    fi

    # Check project-local wikis first
    local project_base
    project_base="$(project_wikis_dir)"
    if [[ -n "$project_base" && -d "$project_base/$input" ]]; then
        echo "$project_base/$input"
        return 0
    fi

    # Fall back to global
    base="$(default_wikis_dir)"
    if [[ -d "$base/$input" ]]; then
        echo "$base/$input"
        return 0
    fi

    return 1
}

require_cmd() {
    local cmd="$1"
    local hint="${2:-}"
    if ! command -v "$cmd" >/dev/null 2>&1; then
        if [[ -n "$hint" ]]; then
            die "Missing required command '$cmd'. $hint"
        fi
        die "Missing required command '$cmd'."
    fi
}

detect_platform() {
    local os
    os="$(uname -s 2>/dev/null || echo unknown)"
    case "$os" in
        Darwin)
            echo "darwin"
            ;;
        Linux)
            echo "linux"
            ;;
        MINGW*|MSYS*|CYGWIN*)
            echo "windows"
            ;;
        *)
            echo "unknown"
            ;;
    esac
}

open_url() {
    local url="$1"

    if command -v open >/dev/null 2>&1; then
        open "$url" >/dev/null 2>&1 || true
        return 0
    fi

    if command -v xdg-open >/dev/null 2>&1; then
        xdg-open "$url" >/dev/null 2>&1 || true
        return 0
    fi

    if command -v start >/dev/null 2>&1; then
        start "$url" >/dev/null 2>&1 || true
        return 0
    fi

    log_warn "Could not auto-open browser. Open this URL manually: $url"
}

generate_mkdocs_project() {
    local wiki_path="$1"
    local project_dir="$2"
    local site_title="$3"
    local docs_dir="$project_dir/docs"
    local config_file="$project_dir/mkdocs.yml"
    local dir
    local file

    rm -rf "$project_dir"
    mkdir -p "$docs_dir"

    cp -R "$wiki_path/." "$docs_dir/"

    {
        echo "site_name: \"$site_title\""
        echo "site_description: \"Generated by deep-codebase-wiki\""
        echo "use_directory_urls: false"
        echo "nav:"
    } > "$config_file"

    if [[ -f "$docs_dir/overview.md" ]]; then
        echo "  - Overview: overview.md" >> "$config_file"
    fi

    for dir in systems components traces; do
        if [[ -d "$docs_dir/$dir" ]]; then
            shopt -s nullglob
            local files=("$docs_dir/$dir"/*.md)
            shopt -u nullglob
            if [[ ${#files[@]} -gt 0 ]]; then
                local title
                title="$(tr '[:lower:]' '[:upper:]' <<< "${dir:0:1}")${dir:1}"
                echo "  - $title:" >> "$config_file"
                for file in "${files[@]}"; do
                    local name
                    name="$(basename "$file" .md)"
                    name="${name//-/ }"
                    echo "      - \"$name\": $dir/$(basename "$file")" >> "$config_file"
                done
            fi
        fi
    done

    if [[ -f "$docs_dir/metadata.yaml" ]]; then
        echo "  - Metadata: metadata.yaml" >> "$config_file"
    fi
}

iso8601_to_epoch() {
    local timestamp="$1"

    if date -u -j -f "%Y-%m-%dT%H:%M:%SZ" "$timestamp" +%s >/dev/null 2>&1; then
        date -u -j -f "%Y-%m-%dT%H:%M:%SZ" "$timestamp" +%s
        return 0
    fi

    if date -u -d "$timestamp" +%s >/dev/null 2>&1; then
        date -u -d "$timestamp" +%s
        return 0
    fi

    if command -v python3 >/dev/null 2>&1; then
        python3 - <<'PY' "$timestamp"
import sys
from datetime import datetime, timezone

value = sys.argv[1]
normalized = value.replace("Z", "+00:00")
try:
    dt = datetime.fromisoformat(normalized)
except ValueError:
    sys.exit(1)

if dt.tzinfo is None:
    dt = dt.replace(tzinfo=timezone.utc)

print(int(dt.timestamp()))
PY
        return $?
    fi

    return 1
}
